services:
  next:
    build:
      context: .
      target: runner-next
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NEST_API_URL=http://nest:3200/v2
    depends_on:
      nest:
        condition: service_healthy
    restart: unless-stopped

  nest:
    build:
      context: .
      target: runner-nest
    ports:
      - "3200:3200"
    env_file:
      - .env
    restart: unless-stopped
