services:
  next:
    build:
      context: .
      target: runner-next
    env_file:
      - .env
    ports:
      - "${PORT_NEXT:-3000}:3000"
    environment:
      - PORT=3000
      - NEST_API_URL=http://nest:3200/v2
    depends_on:
      nest:
        condition: service_healthy
    restart: unless-stopped

  nest:
    build:
      context: .
      target: runner-nest
    ports:
      - "${PORT_NEST:-3200}:3200"
    env_file:
      - .env
    restart: unless-stopped
