import { Metadata } from 'next'
import Image from 'next/image'
import styles from './page.module.css'

export const metadata: Metadata = {
  title: 'wuh.site · 驿寄梅花,鱼传尺素 · wuh.site',
  description: 'Generated by create next app'
}
export default function Home() {
  return (
    <div className={styles.page}>
      <main className={styles.main}>
        <Image className={styles.logo} src='/logo.svg' alt='wuh.site.logo' width={200} height={120} priority />
        <div className={styles.intro}>
          <h1>一个简单的前端开发工程师~~</h1>
          <p>a body, just~~</p>
          <p>React爱好者</p>
          <p>用Vue来搬砖的vuer</p>
        </div>
        <div className={styles.ctas}>
          <a className={styles.primary} href='https://stack-wuh.github.io/blog/' target='_blank' rel='noopener noreferrer'>
            <Image className={styles.logo} src='/vercel.svg' alt='Vercel logomark' width={16} height={16} />
            知识库
          </a>
        </div>
      </main>
    </div>
  )
}
