import type { Metadata } from "next";
import StyledComponentsRegistry from '@wuh.site/components/themes/registry'
import Layout from '@wuh.site/components/layout/index'
import '@wuh.site/components/themes/global.scss';

export const metadata: Metadata = {
  title: "首页·吴尒红的个人博客 - wuh.site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <StyledComponentsRegistry>
          <Layout.Main>
            { children }
          </Layout.Main>
        </StyledComponentsRegistry>
    </html>
  );
}
